steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-api:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'sql'
      - 'connect'
      - 'desafio-api-pedra-pagamentos:us-central1:api-pedra-db-01' 
      - '--user=postgres'
      - '--password=$POSTGRES_PASSWORD'
      - '--database=postgres'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-tests:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloudsql-docker/gce-proxy:latest'
    entrypoint: '/cloud_sql_proxy'
    args:
      - '-dir=/cloudsql'
      - '-credential_file=/secrets/cloudsql/credentials.json'  
      - 'tcp:5432' 
    secretEnv:
      - DATABASE_URL  

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - 'cloudsql:cloudsql'
      - 'gcr.io/$PROJECT_ID/my-tests:$COMMIT_SHA'
      - 'pytest'
      - '/app/tests'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'stop'
      - 'postgres'

images:
  - 'gcr.io/$PROJECT_ID/my-api:$COMMIT_SHA'
