steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-api:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-tests:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloudsql-docker/gce-proxy:latest'
    entrypoint: '/cloud_sql_proxy'
    args:
      - '-dir=/cloudsql'
      - '-credential_file=/secrets/cloudsql/credentials.json'  # A autenticação para o Cloud SQL
      - 'tcp:5432'  # Usando a porta padrão para PostgreSQL
    secretEnv:
      - DATABASE_URL  # O segredo armazenado no Secret Manager

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '--link'
      - 'cloudsql:cloudsql'  # Linkando o Cloud SQL Proxy ao contêiner
      - 'gcr.io/$PROJECT_ID/my-tests:$COMMIT_SHA'
      - 'pytest'
      - '/app/tests'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'stop'
      - 'postgres'

images:
  - 'gcr.io/$PROJECT_ID/my-api:$COMMIT_SHA'
