services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - "./src:/app"
      - "./data:/src/infrastructure/data"
    ports:
      - "5000:5000" 
    environment:
     - DATABASE_URL=${DATABASE_URL} 
    depends_on:
      - db
    command: ["sh", "-c", "python /scripts/load_data.py && gunicorn --reload -b 0.0.0.0:5000 app:app"]

  db:
    image: postgres:latest  
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

volumes:
  postgres_data:
