services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - "./src:/app"
      - "./src/infrastructure/data:/app/infrastructure/data"
    ports:
      - "8080:8080" 
    environment:
     - DATABASE_URL=${DATABASE_URL} 
     - TOKEN=${TOKEN}
     - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    restart: unless-stopped
    command: ["sh", "-c", "python /app/src/infrastructure/scripts/main.py && gunicorn --reload -b 0.0.0.0:$PORT app.app:app"]

  db:
    image: postgres:latest  
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/app"
    command: ["pytest", "/app/tests"]
    depends_on:
      - api

volumes:
  postgres_data:
